### ISSUE TITLE
Low resolution images in print output

### ISSUE THREAD

**Issue by manegame** [kabk/go-theses-17-manus-nijhoff#1]
@codingisacopingstrategy Bij uitvoer van afbeeldingen voor print gaan de afbeeldingen naar een soort 2dpi-achtige look. Heb jij enige ervaring met dit probleem?

**Comment by codingisacopingstrategy** [comment]
Bizar Magda heeft ook zo iets. Het is alleen in Chrome toch? Ik weet niet wat het veroorzaakt, ik zal er nog eens verder naar kijken.

**Comment by manegame** [comment]
ah, ja. Inderdaad alleen in Chrome. Voor mij is de oplossing simpel, ik kan evt. vanuit Safari ook printen :)

**Comment by codingisacopingstrategy** [comment]
Bij Magda zat het probleem in -webkit-filter / filter css regels, daar had de PDF engine in Chrome klaarblijkelijk moeite mee.

**Comment by manegame** [comment]
Ah, die heb ik ook. Werkt idd om die weg te halen in print. Thanks!
